<a href="https://colab.research.google.com/github/dewangsahuji/Deep_Learning_Compu_vision/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with TensorFlow 2
## Einsum Operator

In [ ]:
import numpy as np

In [ ]:
A = np.array([
              [2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]
                        ])

B = np.array([
             [2,9,0,3,0],
             [3,6,8,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]
                          ])

print(A.shape)
print(B.shape)

print("Matmul C=: \n")
print(np.matmul(A,B) , "\n")

print("Einsum C=: \n")
print(np.einsum("ij,jk->ik",A,B) , "\n")



(3, 4)
(4, 5)
Matmul C=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum C=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 



In [ ]:
A = np.array([
              [1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]
                        ])

B = np.array([
             [13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]
                          ])
print(A.shape , B.shape)


print("Hardamond C =: \n")
print(A*B )

print("Einsum C =: \n")
print(np.einsum("ij,ij->ij",A,B))




(3, 4) (3, 4)
Hardamond C =: 

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]
Einsum C =: 

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [ ]:
A = np.array([
              [1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]
                        ])
print("Transposed A=: \n")
print(A.T)

print("Einsum Transposed A=: \n")
print(np.einsum("ij->ji",A))


Transposed A=: 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Einsum Transposed A=: 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
A = np.array([
    [
        [1, 2, 3, 4],
        [6, 7, 8, 9],
        [11, 12, 13, 14],
    ],
    [
        [21, 22, 23, 24],
        [26, 27, 28, 29],
        [31, 32, 33, 34],
    ]
])

B = np.array([
    [
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]
    ],
    [
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75],
        [76, 77, 78, 79, 80]
    ]
])

print(A.shape ,B.shape)

print("Batch Multiplication C=: \n")
print(np.matmul(A,B))

print("Einsum Batch Multiplication C=: \n")
print(np.einsum("bij,bjk->bik",A,B))



(2, 3, 4) (2, 4, 5)
Batch Multiplication C=: 

[[[ 510  520  530  540  550]
  [1480 1510 1540 1570 1600]
  [2450 2500 2550 2600 2650]]

 [[6190 6280 6370 6460 6550]
  [7560 7670 7780 7890 8000]
  [8930 9060 9190 9320 9450]]]
Einsum Batch Multiplication C=: 

[[[ 510  520  530  540  550]
  [1480 1510 1540 1570 1600]
  [2450 2500 2550 2600 2650]]

 [[6190 6280 6370 6460 6550]
  [7560 7670 7780 7890 8000]
  [8930 9060 9190 9320 9450]]]


In [ ]:
A = np.array([
    [
        [1, 2, 3, 4],
        [6, 7, 8, 9],
        [11, 12, 13, 14],
    ],
    [
        [21, 22, 23, 24],
        [26, 27, 28, 29],
        [31, 32, 33, 34],
    ]
])
print("Sum of A =: \n")
print(np.sum(A) )

print("Einsum Sum of A =: \n")
print(np.einsum("ijk-> j",A))




Sum of A =: 

420
Einsum Sum of A =: 

[100 140 180]


In [ ]:
 A = np.random.randn(2,4,4,2) #bcij
 B = np.random.randn(2,4,4,1) #bcik

 print(np.einsum("bcik,bcij -> bckj" , B, A).shape)

(2, 4, 1, 2)


In [ ]:
import tensorflow as tf


In [ ]:
tensor_three_d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(tf.expand_dims(tensor_three_d, axis=1).shape)
print(tensor_three_d)

(2, 1, 2, 2)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
x=tf.constant([[[2,3,4,5]]])
x_sqeeze = tf.squeeze(x , axis=0)
print(x_sqeeze.shape)
print(x_sqeeze)

(1, 4)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [ ]:
x_sqe = tf.squeeze(x_sqeeze,axis=0)
print(x_sqeeze.shape)
print(x_sqeeze)

(1, 4)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [ ]:
tensor_two_d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

tf.reshape(tensor_two_d, [8])

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8])>

In [ ]:
tensor_two_d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

tf.reshape(tensor_two_d, [4,2])

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [ ]:
t1 = np.array([[
    [1, 2, 3],
    [4, 5, 6]
]])

t2 = np.array([[
    [7, 8, 9],
    [10, 11, 12]
]])

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis=1)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(1, 4, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])>

In [ ]:
t1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

t2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

tf.stack([t1,t2] , axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
t1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

t2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

tf.stack([t1,t2] , axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])>

In [ ]:
t1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

t2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

tf.stack([t1,t2] , axis=2)

<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])>

In [ ]:
params = np.array(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])

print(params[1:3+1])

['p1' 'p2' 'p3']


In [ ]:
tf.gather(params, [1, 2, 3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>